// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tthyppsiydfgcdsmiizt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0aHlwcHNpeWRmZ2Nkc21paXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTE0OTAsImV4cCI6MjA2ODQ2NzQ5MH0.4lNTurQ_qUGlQuIpGs7FF7YJPsiMoyNCWT7UDmgxKec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});